[package]
name = "spectre-sidecar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0.0", features = ["full"] }
tokio-tungstenite = "0.26.2"
dirs = "6.0.0"
regex = "1.11.1"
tungstenite = "0.26.2"
futures = "0.3.31"
